version: '3'

services:
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017-27019:27017-27019
    volumes:
      - /var/lib/mongodb:/data/db

  redis:
    image: redis
    restart: always
    ports:
      - 6379:6379
    volumes:
      - .docker/redis-volume:/data/

  metrics:
    build: ../metrics
    restart: always

    ports:
      - 4050:4050

  gateway:
    build: ../gateway
    restart: always

    ports:
      - 4200:4200

  bot:
    build: .
    restart: always

    depends_on:
      - gateway

  api:
    build: ../api
    restart: always

    depends_on:
      - mongo
      - gateway
    ports:
      - 4011:4011

  feeds:
    build: ../feed-handler
    restart: always

    depends_on:
      - gateway
      - api
      - redis
    ports:
      - 4014:4014
      - 4015:4015

  interactions:
    build: ../interactions
    restart: always

    depends_on:
      - gateway
    ports:
      - 4017:4017